# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  rg_name: 'tfstate'
  rem_storage_account_name: 'tfstate1048584424'
  rem_container_name: 'tfstate'
  rem_key: 'terraform.tfstate'

stages:
  - stage: tfvalidate
    jobs: 
      - job: validate
        continueOnError: false
        steps:
          - task: TerraformTaskV3@3
            displayName: Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'serv-conn'
              backendAzureRmResourceGroupName: '$(rg_name)'
              backendAzureRmStorageAccountName: '$(rem_storage_account_name)'
              backendAzureRmContainerName: '$(rem_container_name)'
              backendAzureRmKey: '$(rem_key)'
          - task: TerraformTaskV3@3
            displayName: Validate
            inputs:
              provider: 'azurerm'
              command: 'validate'
  - stage: tfplan
    condition: succeeded('tfvalidate')
    dependsOn: tfvalidate
    jobs:
      - job: plan
        steps:
          - task: TerraformTaskV3@3
            displayName: Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'serv-conn'
              backendAzureRmResourceGroupName: '$(rg_name)'
              backendAzureRmStorageAccountName: '$(rem_storage_account_name)'
              backendAzureRmContainerName: '$(rem_container_name)'
              backendAzureRmKey: '$(rem_key)'
          - task: TerraformTaskV3@3
            displayName: Plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              commandOptions: '-out main.tfplan'
              environmentServiceNameAzureRM: 'serv-conn'
  - stage: tfapply
    condition: succeeded('tfplan')
    dependsOn: tfplan
    jobs:
      - job: apply
        steps:
          - task: TerraformTaskV3@3
            displayName: Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'serv-conn'
              backendAzureRmResourceGroupName: '$(rg_name)'
              backendAzureRmStorageAccountName: '$(rem_storage_account_name)'
              backendAzureRmContainerName: '$(rem_container_name)'
              backendAzureRmKey: '$(rem_key)'
              
          - task: TerraformTaskV3@3
            displayName: Apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              commandOptions: 'main.tfplan'
              environmentServiceNameAzureRM: 'serv-conn'

