# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'serv-conn'
    KeyVaultName: 'serviceapp-kv'
    SecretsFilter: '*'
    RunAsPreJob: true
  env:
    ARM_ACCESS_KEY: $(storage) 
    ARM_222: "222"

- task: CmdLine@2
  inputs:
    script: |
      echo $(storage)      
  