# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'pipeline-connection'
    KeyVaultName: 'serviceapp-kv'
    SecretsFilter: 'storage'
    RunAsPreJob: true
  displayName: 'Show secret'
  env:
    ARM_ACCESS_KEY: $(storage)
  
- script: |
    echo "Secret: $ARM_ACCESS_KEY"